//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string IDAccount { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
        public string PhanQuyen { get; set; }
    }
}
