//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatDichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatDichVu()
        {
            this.DatDichVuChiTiets = new HashSet<DatDichVuChiTiet>();
        }
    
        public string IDDatDV { get; set; }
        public string IDKH { get; set; }
        public string IDDV { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatDichVuChiTiet> DatDichVuChiTiets { get; set; }
        public virtual DichVu DichVu { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
