//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatDichVu
    {
        public string IDDatDV { get; set; }
        public string IDHD { get; set; }
        public string IDDV { get; set; }
        public Nullable<System.DateTime> NgaySD { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
