//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public string IDDatPHG { get; set; }
        public string IDHD { get; set; }
        public string IDPHG { get; set; }
        public System.DateTime NgayNhan { get; set; }
        public System.DateTime NgayTra { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
