//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_HotelManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonChiTiet
    {
        public string IDHDChiTiet { get; set; }
        public string IDHD { get; set; }
        public string IDDatDVChiTiet { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        public virtual DatDichVuChiTiet DatDichVuChiTiet { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
