//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_HotelManagementSystem.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiDV
    {
        public LoaiDV()
        {
            this.DichVus = new HashSet<DichVu>();
        }

        [Key]
        public string IDLoaiDV { get; set; }
        public string TenLoaiDV { get; set; }
        public double DonGia { get; set; }
        public int SoNguoi { get; set; }

        [JsonIgnore]
        public virtual ICollection<DichVu> DichVus { get; set; }
    }
}
